services:
  servermonitor-backend:
    image: servermonitor-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        DB_URL: ${DB_URL}
        DB_USERNAME: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    container_name: servermonitor-backend
    ports:
      - "8052:8052"
    networks:
      - servermonitor-net
    restart: unless-stopped

networks:
  servermonitor-net:
    name: servermonitor-net
